In [2]:
import torch

In [3]:
x = torch.rand([10,2])
x

tensor([[0.9235, 0.4757],
        [0.1888, 0.8513],
        [0.4574, 0.1979],
        [0.0652, 0.6204],
        [0.0934, 0.8857],
        [0.0917, 0.4329],
        [0.5456, 0.9257],
        [0.8596, 0.7412],
        [0.8431, 0.8585],
        [0.3141, 0.7433]])

In [4]:
mask = torch.tensor([[1,0]]).to(x)
mask

tensor([[1., 0.]])

In [5]:
mask*x +

tensor([[0.9235, 0.0000],
        [0.1888, 0.0000],
        [0.4574, 0.0000],
        [0.0652, 0.0000],
        [0.0934, 0.0000],
        [0.0917, 0.0000],
        [0.5456, 0.0000],
        [0.8596, 0.0000],
        [0.8431, 0.0000],
        [0.3141, 0.0000]])